## Advantages of Weibull Analysis

The primary advantage ofWeibull analysis is the ability to provide reasonably accurate failure analysis and failure forecasts with extremely small samples. Solutions are possible at the earliest indications of a problem without having to "crash a few more." Small samples also allow cost effective component testing. For example, "sudden death" Weibull tests are completed when the first failure occurs in each group of components, (say, groups of four bearings). If all the bearings are tested to failure, the cost and time required is much greater.   

Another advantage of Weibull analysis is that it provides a simple and useful graphical plot of the failure data. The data plot is extremely important to the engineer and to the manager. The Weibull data plot is particularly informative as Weibull pointed out in his 1951 paper. The plot in this tab is a typical Weibull plot.   

The horizontal scale is a measure of life or aging. Start/stop cycles, mileage, operating time, landings or mission cycles are examples of aging parameters. The vertical scale is the cumulative percentage failed. The two defining parameters of the Weibull line are the slope ($\beta$) and the characteristic life (eta).  
  + The slope of the line, beta, is particularly significant and may provide a clue to the physics of the failure. 
  + The characteristic life, eta , is the typical time to failure in Weibull analysis. It is related to the mean time to failure.

The following are examples of engineering problems solved with Weibull analysis:
  + A project engineer reports three failures of a component in service operations during a three-month period. The Program Manager asks, "How many failures will we have in the next quarter, six months, and year?" What will it cost? What is the best corrective action to reduce the risk and losses?  
  + To order spare parts and schedule maintenance labor, how many units will be returned to depot for overhaul for each failure mode month-by-month next year? The program manager wants to be 95% confident that he will have enough spare parts and labor available to support the overall program. A state Air Resources Board requires a fleet recall when any part in the emissions system exceeds a 4% failure rate during the warranty period. Based on the warranty data, which parts will exceed
the 4% rate and on what date?   
  + After an engineering change, how many units must be tested for how long, without any failures, to verify that the old failure mode is eliminated, or significantly improved with 90% confidence?   
  + An electric utility is plagued with outages from superheater tube failures. Based on inspection data forecast the life of the boiler based on plugging failed tubes. The boiler is replaced when 10% of the tubes have been plugged due to failure.  
  + The cost of an unplanned failure for a component, subject to a wear out failure mode, is twenty times the cost of a planned replacement. What is the optimal replacement interval?  
  
  